using System.Collections.Generic;
using System.Threading.Tasks;
using Domain;

namespace WebAPI.Repositories
{
    public interface IMeasurementRepository
    {
        /// <summary>
        /// Returns all measurements generated by the devices in a specific room 
        /// </summary>
        /// <param name="roomId">id of the room</param>
        /// <returns>Aggregated list of measurement</returns>
        Task<IEnumerable<Measurement>> GetByRoomIdAsync(int roomId);

        /// <summary>
        /// Returns all measurements generated by the devices in a specific room
        /// </summary>
        /// <param name="roomName">Name of the room. Currently room names follow the pattern [A-Z][0-9][0-9]_[0-9][0-9][a-z]?$. E.g. C02_02a / CO2_02</param>
        /// <returns>Aggregated list of measurement</returns>
        Task<IEnumerable<Measurement>> GetByRoomNameAsync(string roomName);

        /// <summary>
        /// Stores the measurements a device has generated
        /// </summary>
        /// <param name="deviceId">Id of the Climate Device that generated the measurements</param>
        /// <param name="measurements">The measurements the device has generated</param>
        Task AddMeasurements(string deviceId, IEnumerable<Measurement> measurements);
    }
}